# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.trace.com:
  peer0.traceorg1.trace.com:
  peer1.traceorg1.trace.com:
  peer0.traceorg2.trace.com:
  peer1.traceorg2.trace.com:

networks:
  traceNetwotk-v1:

services:

  orderer.trace.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.trace.com
    container_name: orderer.trace.com
    networks:
      - traceNetwotk-v1

  peer0.traceorg1.trace.com:
    container_name: peer0.traceorg1.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.traceorg1.trace.com
    networks:
      - traceNetwotk-v1

  peer1.traceorg1.trace.com:
    container_name: peer1.traceorg1.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.traceorg1.trace.com
    networks:
      - traceNetwotk-v1

  peer0.traceorg2.trace.com:
    container_name: peer0.traceorg2.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.traceorg2.trace.com
    networks:
      - traceNetwotk-v1

  peer1.traceorg2.trace.com:
    container_name: peer1.traceorg2.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.traceorg2.trace.com
    networks:
      - traceNetwotk-v1

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.traceorg1.trace.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/traceorg1.trace.com/peers/peer0.traceorg1.trace.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/traceorg1.trace.com/peers/peer0.traceorg1.trace.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/traceorg1.trace.com/peers/peer0.traceorg1.trace.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/traceorg1.trace.com/users/Admin@traceorg1.trace.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.trace.com
      - peer0.traceorg1.trace.com
      - peer1.traceorg1.trace.com
      - peer0.traceorg2.trace.com
      - peer1.traceorg2.trace.com
    networks:
      - traceNetwotk-v1
