# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.trace.com:
  peer0.traceorg1.trace.com:
  peer1.traceorg1.trace.com:
  peer0.traceorg2.trace.com:
  peer1.traceorg2.trace.com:

networks:
  traceNetwotk-v1:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-traceorg1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.traceorg1.trace.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.traceorg1.trace.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/traceorg1.trace.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - traceNetwotk-v1

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-traceorg2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.traceorg2.trace.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.traceorg2.trace.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/traceorg2.trace.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - traceNetwotk-v1

  orderer.trace.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.trace.com
    container_name: orderer.trace.com
    networks:
      - traceNetwotk-v1

  peer0.traceorg1.trace.com:
    container_name: peer0.traceorg1.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.traceorg1.trace.com
    networks:
      - traceNetwotk-v1

  peer1.traceorg1.trace.com:
    container_name: peer1.traceorg1.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.traceorg1.trace.com
    networks:
      - traceNetwotk-v1

  peer0.traceorg2.trace.com:
    container_name: peer0.traceorg2.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.traceorg2.trace.com
    networks:
      - traceNetwotk-v1

  peer1.traceorg2.trace.com:
    container_name: peer1.traceorg2.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.traceorg2.trace.com
    networks:
      - traceNetwotk-v1
